apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: demoapp
        image: omeshwar/harness-training:test
        ports:
        - containerPort: 8080
